name: memesworld

description: A social media app dedicated to sharing and exploring memes.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  firebase_storage: ^13.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.2.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  uuid: ^4.5.1
  universal_html: ^2.2.4
  firebase_database: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/memesworld.png
