// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnG_LWQsWOy_bm8JGWe7vFwEOFffiVeh4',
    appId: '1:690366703212:web:6efab1a41e5e7a54711a49',
    messagingSenderId: '690366703212',
    projectId: 'memesworld-e29a3',
    authDomain: 'memesworld-e29a3.firebaseapp.com',
    databaseURL: 'https://memesworld-e29a3-default-rtdb.firebaseio.com',
    storageBucket: 'memesworld-e29a3.firebasestorage.app',
    measurementId: 'G-EEM1JE1E3F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYZ2nBGXpeWvUqI5kf_3wq4XLeZaiG2vg',
    appId: '1:690366703212:android:dafd567f23dfcf1a711a49',
    messagingSenderId: '690366703212',
    projectId: 'memesworld-e29a3',
    databaseURL: 'https://memesworld-e29a3-default-rtdb.firebaseio.com',
    storageBucket: 'memesworld-e29a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1-EfEoDlhTetxlCh5Aot48YSzXUck8aQ',
    appId: '1:690366703212:ios:67a9f1982e68f40d711a49',
    messagingSenderId: '690366703212',
    projectId: 'memesworld-e29a3',
    databaseURL: 'https://memesworld-e29a3-default-rtdb.firebaseio.com',
    storageBucket: 'memesworld-e29a3.firebasestorage.app',
    iosBundleId: 'com.example.memesworld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1-EfEoDlhTetxlCh5Aot48YSzXUck8aQ',
    appId: '1:690366703212:ios:67a9f1982e68f40d711a49',
    messagingSenderId: '690366703212',
    projectId: 'memesworld-e29a3',
    databaseURL: 'https://memesworld-e29a3-default-rtdb.firebaseio.com',
    storageBucket: 'memesworld-e29a3.firebasestorage.app',
    iosBundleId: 'com.example.memesworld',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnG_LWQsWOy_bm8JGWe7vFwEOFffiVeh4',
    appId: '1:690366703212:web:ff235adad9a07eb1711a49',
    messagingSenderId: '690366703212',
    projectId: 'memesworld-e29a3',
    authDomain: 'memesworld-e29a3.firebaseapp.com',
    databaseURL: 'https://memesworld-e29a3-default-rtdb.firebaseio.com',
    storageBucket: 'memesworld-e29a3.firebasestorage.app',
    measurementId: 'G-FGEXCTSNZH',
  );
}
