// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOyYZTPHi1hAFCLoIdMeEb6vUmK58XaDc',
    appId: '1:161247614384:web:29a9edcf8fc3061eab3275',
    messagingSenderId: '161247614384',
    projectId: 'memesworld-9fa23',
    authDomain: 'memesworld-9fa23.firebaseapp.com',
    databaseURL: 'https://memesworld-9fa23-default-rtdb.firebaseio.com',
    storageBucket: 'memesworld-9fa23.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOyYZTPHi1hAFCLoIdMeEb6vUmK58XaDc',
    appId: '1:161247614384:android:29a9edcf8fc3061eab3275',
    messagingSenderId: '161247614384',
    projectId: 'memesworld-9fa23',
    databaseURL: 'https://memesworld-9fa23-default-rtdb.firebaseio.com',
    storageBucket: 'memesworld-9fa23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOyYZTPHi1hAFCLoIdMeEb6vUmK58XaDc',
    appId: '1:161247614384:ios:29a9edcf8fc3061eab3275',
    messagingSenderId: '161247614384',
    projectId: 'memesworld-9fa23',
    databaseURL: 'https://memesworld-9fa23-default-rtdb.firebaseio.com',
    storageBucket: 'memesworld-9fa23.appspot.com',
    iosBundleId: 'com.company.memesworld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOyYZTPHi1hAFCLoIdMeEb6vUmK58XaDc',
    appId: '1:161247614384:ios:29a9edcf8fc3061eab3275',
    messagingSenderId: '161247614384',
    projectId: 'memesworld-9fa23',
    databaseURL: 'https://memesworld-9fa23-default-rtdb.firebaseio.com',
    storageBucket: 'memesworld-9fa23.appspot.com',
    iosBundleId: 'com.company.memesworld',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOyYZTPHi1hAFCLoIdMeEb6vUmK58XaDc',
    appId: '1:161247614384:web:29a9edcf8fc3061eab3275',
    messagingSenderId: '161247614384',
    projectId: 'memesworld-9fa23',
    authDomain: 'memesworld-9fa23.firebaseapp.com',
    databaseURL: 'https://memesworld-9fa23-default-rtdb.firebaseio.com',
    storageBucket: 'memesworld-9fa23.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );
}
